export const CONDUCTOR_MAX_PLAN_TASKS = 12;
export const CONDUCTOR_MAX_PLAN_SUBTASKS_PER_PARENT = 4;
export const CONDUCTOR_MAX_WORKER_FOLLOW_UP_TASKS = 2;
export const CONDUCTOR_MAX_REVIEW_FOLLOW_UP_TASKS = 2;
